In [ ]:
print("unexpected")

unexpected


In [6]:
smthing = [1,2,4, (2,3,4,5, {"key": [1,2,3,4, {"key2": (234, 456)}]})]

In [8]:
smthing[-1][-1]["key"][-1]["key2"][-1]

456

In [10]:
name = "Alice"
Status = "Passed"

if Status == "Passed":
    print(f"{name} has passed the exam.")
else:
    print(f"{name} has not passed the exam.")

Alice has passed the exam.


In [12]:
[print(x) for x in range(10)]

0
1
2
3
4
5
6
7
8
9


[None, None, None, None, None, None, None, None, None, None]

In [13]:
x = []
y = []

sumx = 0
sumy = 0

for i in x:
    sumx += i

for i in y:
    sumy += i

mean_x = sumx / len(x)
mean_y = sumy / len(y)

numerator = 0

for i in range(len(x)):
    numerator += (x[i] - mean_x) * (y[i] - mean_y)

denominator_x = 0
denominator_y = 0

for i in range(len(x)):
    denominator_x += (x[i] - mean_x) ** 2
    denominator_y += (y[i] - mean_y) ** 2

denominator = (denominator_x * denominator_y) ** 0.5

correlation = numerator / denominator

ZeroDivisionError: division by zero

In [18]:
dates = ['Fri, Jan 17-Sat, Jan 18', 'Fri, Feb 7', 'Fri, Feb 7', 'Fri, Feb 14', 'Thu, Feb 20', 'Fri, Feb 28', 'Wed, Mar 5', 'Sat, Mar 15', 'Sat, Mar 22', 'Sat, Mar 29']
year = 2025
for date in dates:
    date = f"{date.split('-')[0].split(',')[1].strip()} {year}"
    print(date)

Jan 17 2025
Feb 7 2025
Feb 7 2025
Feb 14 2025
Feb 20 2025
Feb 28 2025
Mar 5 2025
Mar 15 2025
Mar 22 2025
Mar 29 2025


In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 0]])

In [12]:
import random

counter_success = 0

for i in range(10000):
    person_a_choice = random.randint(0,15)
    person_b_choice = random.randint(0,15)
    if person_a_choice == person_b_choice:
        counter_success+=1


In [14]:
counter_success/10000

0.0642

In [24]:
import numpy as np

a = np.array([[[1, 2, 3]], [[4, 5, 0]]])

In [32]:
text1 = "Apples are red"
text2 = "Apples are sweet"
text3 = "Oranges are sweet"

In [33]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

sw_nltk = stopwords.words('english')
lemmatizer = WordNetLemmatizer()

text1 = " ".join([lemmatizer.lemmatize(word) for word in nltk.word_tokenize(text1.lower()) if word not in sw_nltk])
text2 = " ".join([lemmatizer.lemmatize(word) for word in nltk.word_tokenize(text2.lower()) if word not in sw_nltk])
text3 = " ".join([lemmatizer.lemmatize(word) for word in nltk.word_tokenize(text3.lower()) if word not in sw_nltk])

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tanmayshubhgarg/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/tanmayshubhgarg/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/tanmayshubhgarg/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [38]:
total = set(text1.lower().split(" ") + text2.lower().split(" ") + text3.lower().split(" "))
print(total)
total = list(total)

{'orange', 'sweet', 'apple', 'red'}


In [87]:
import pandas as pd

df = pd.DataFrame(0, index=total, columns=total)

In [88]:
def makecm(corpus):
    df = pd.DataFrame(0, index=total, columns=total)
    for text in corpus:
        words = text.split(" ")
        for word in words:
            try:
                if words[1 + words.index(word)] in total:
                    df.at[words[1 + words.index(word)], word] += 1
                if words[-1 + words.index(word)] in total:
                    df.at[word, words[-1 + words.index(word)]] += 1
            except IndexError:
                continue
    return df

text1words = text1.split(" ")
for word in text1words:
    try:
        if text1words[1+text1words.index(word)] in total:
            df.at[text1words[1+text1words.index(word)], word] += 1
        if text1words[-1 + text1words.index(word)] in total:
            df.at[word, text1words[-1 + text1words.index(word)]] += 1
    except IndexError:
        continue



In [89]:
df

orange  sweet  apple  red
orange       0      0      0    0
sweet        0      0      0    0
apple        0      0      0    1
red          0      0      1    0

In [90]:
text2words = text2.split(" ")
for word in text2words:
    try:
        if text2words[1+text2words.index(word)] in total:
            df.at[text2words[1+text2words.index(word)], word] += 1
        if text2words[-1 + text2words.index(word)] in total:
            df.at[word, text2words[-1 + text2words.index(word)]] += 1
    except IndexError:
        continue


In [91]:
df

orange  sweet  apple  red
orange       0      0      0    0
sweet        0      0      1    0
apple        0      1      0    1
red          0      0      1    0

In [92]:
text3words = text3.split(" ")
for word in text3words:
    try:
        if text3words[1+text3words.index(word)] in total:
            df.at[text3words[1+text3words.index(word)], word] += 1
        if text3words[-1 + text3words.index(word)] in total:
            df.at[word, text3words[-1 + text3words.index(word)]] += 1
    except IndexError:
        continue

In [93]:
df

orange  sweet  apple  red
orange       0      1      0    0
sweet        1      0      1    0
apple        0      1      0    1
red          0      0      1    0

In [94]:
cm = np.array(df)

In [95]:
cm

array([[0, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 0]])

In [96]:
corpus = [text1, text2, text3]
cm = makecm(corpus)
print(cm)

        orange  sweet  apple  red
orange       0      1      0    0
sweet        1      0      1    0
apple        0      1      0    1
red          0      0      1    0


In [97]:
cm_array = np.array(cm)

In [98]:
cm_array

array([[0, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 0]])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

array([[1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 1]])

In [107]:
X = cm_array
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
dense_vector = pca.fit_transform(X)

In [108]:
dense_vector

array([[ 0.60150096, -0.35355339],
       [-0.97324899,  0.35355339],
       [ 0.97324899,  0.35355339],
       [-0.60150096, -0.35355339]])

In [110]:
from numpy.linalg import svd
from itertools import combinations

In [112]:
U, s, Vt = svd(dense_vector, full_matrices=False)
U2 = U[:, :2]
S2 = np.diag(s[:2])
embeddings = U2 @ S2

In [116]:
U2

array([[-0.37174803,  0.5       ],
       [ 0.60150096, -0.5       ],
       [-0.60150096, -0.5       ],
       [ 0.37174803,  0.5       ]])

In [118]:
s

array([1.61803399, 0.70710678])

In [119]:
S2

array([[1.61803399, 0.        ],
       [0.        , 0.70710678]])

In [120]:
Vt

array([[-1., -0.],
       [-0., -1.]])

In [121]:
embeddings

array([[-0.60150096,  0.35355339],
       [ 0.97324899, -0.35355339],
       [-0.97324899, -0.35355339],
       [ 0.60150096,  0.35355339]])

In [122]:
def cos_sim(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))


In [125]:
for i, j in combinations(range(len(total)), 2):
    sim = cos_sim(dense_vector[i], dense_vector[j])
    print(f"{total[i]} and {total[j]}: {sim:.4f}")

orange and sweet: -0.9833
orange and apple: 0.6373
orange and red: -0.4864
sweet and apple: -0.7668
sweet and red: 0.6373
apple and red: -0.9833


In [126]:
for i, j in combinations(range(len(total)), 2):
    sim = cos_sim(embeddings[i], embeddings[j])
    print(f"{total[i]} and {total[j]}: {sim:.4f}")

orange and sweet: -0.9833
orange and apple: 0.6373
orange and red: -0.4864
sweet and apple: -0.7668
sweet and red: 0.6373
apple and red: -0.9833
